### ISSUE TITLE
I can't find the env file

### ISSUE THREAD

**Issue by junge1a520** [houchangmeng/CarlaAutoParking#1]
for example: from env.parking_carla_env import CarlaEnv

**Comment by houchangmeng** [comment]
sorry, i forgeted to upload that folder...

**Comment by junge1a520** [comment]
> sorry, i forgeted to upload that folder...

Pls when can you upload it, I want to test your program，thank you.

**Comment by houchangmeng** [comment]
I already upload that folder.
